;ORG $1C00
; $1C00 Character set
.CharacterSet1
; char_sprite_1 $00
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $40 ; .#......
EQUB $00 ; ........

; char_sprite_2 $01
EQUB $7C ; .#####..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $7C ; .#####..
EQUB $44 ; .#...#..
EQUB $46 ; .#...##.
EQUB $46 ; .#...##.
EQUB $46 ; .#...##.

; char_sprite_3 $02
EQUB $78 ; .####...
EQUB $48 ; .#..#...
EQUB $48 ; .#..#...
EQUB $7C ; .#####..
EQUB $44 ; .#...#..
EQUB $46 ; .#...##.
EQUB $46 ; .#...##.
EQUB $7E ; .######.
    
; char_sprite_4 $03
EQUB $78 ; .####...
EQUB $48 ; .#..#...
EQUB $4C ; .#..##..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $46 ; .#...##.
EQUB $46 ; .#...##.
EQUB $7E ; .######.
    
; char_sprite_5 $04
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $46 ; .#...##.
EQUB $46 ; .#...##.
EQUB $7E ; .######.

; char_sprite_6 $05
EQUB $3E ; ..#####.
EQUB $20 ; ..#.....
EQUB $20 ; ..#.....
EQUB $20 ; ..#.....
EQUB $20 ; ..#.....
EQUB $60 ; .##.....
EQUB $60 ; .##.....
EQUB $7E ; .######.

; char_sprite_7 $06
EQUB $7C ; .#####..
EQUB $10 ; ...#....
EQUB $10 ; ...#....
EQUB $10 ; ...#....
EQUB $10 ; ...#....
EQUB $30 ; ..##....
EQUB $30 ; ..##....
EQUB $30 ; ..##....

; char_sprite_8 $07
EQUB $7C ; .#####..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $46 ; .#...##.
EQUB $46 ; .#...##.
EQUB $7E ; .######.

; char_sprite_9 $08
EQUB $38 ; ..###...
EQUB $24 ; ..#..#..
EQUB $24 ; ..#..#..
EQUB $38 ; ..###...
EQUB $30 ; ..##....
EQUB $68 ; .##.#...
EQUB $66 ; .##..##.
EQUB $66 ; .##..##.

; char_sprite_10 $09
EQUB $3C ; ..####..
EQUB $10 ; ...#....
EQUB $91 ; #..#...#
EQUB $9F ; #..#####
EQUB $F9 ; #####..#
EQUB $89 ; #...#..#
EQUB $08 ; ....#...
EQUB $3C ; ..####..

; char_sprite_11 $0A
EQUB $18 ; ...##...
EQUB $46 ; .#...##.
EQUB $48 ; .#..#...
EQUB $B9 ; #.###..#
EQUB $9D ; #..###.#
EQUB $12 ; ...#..#.
EQUB $62 ; .##...#.
EQUB $18 ; ...##...

; char_sprite_12 $0B
EQUB $24 ; ..#..#..
EQUB $42 ; .#....#.
EQUB $A5 ; #.#..#.#
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $A5 ; #.#..#.#
EQUB $42 ; .#....#.
EQUB $24 ; ..#..#..

; char_sprite_13 $0C
EQUB $18 ; ...##...
EQUB $62 ; .##...#.
EQUB $12 ; ...#..#.
EQUB $9D ; #..###.#
EQUB $B9 ; #.###..#
EQUB $48 ; .#..#...
EQUB $46 ; .#...##.
EQUB $18 ; ...##...

; char_sprite_14 $0D
EQUB $00 ; ........
EQUB $3C ; ..####..
EQUB $24 ; ..#..#..
EQUB $A5 ; #.#..#.#
EQUB $A5 ; #.#..#.#
EQUB $24 ; ..#..#..
EQUB $3C ; ..####..
EQUB $00 ; ........

; char_sprite_15 $0E
EQUB $10 ; ...#....
EQUB $58 ; .#.##...
EQUB $94 ; #..#.#..
EQUB $24 ; ..#..#..
EQUB $28 ; ..#.#...
EQUB $49 ; .#..#..#
EQUB $72 ; .###..#.
EQUB $10 ; ...#....

; char_sprite_16 $0F
EQUB $24 ; ..#..#..
EQUB $4A ; .#..#.#.
EQUB $91 ; #..#...#
EQUB $22 ; ..#...#.
EQUB $44 ; .#...#..
EQUB $89 ; #...#..#
EQUB $52 ; .#.#..#.
EQUB $24 ; ..#..#..

; char_sprite_17 $10
EQUB $82 ; #.....#.
EQUB $7C ; .#####..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $44 ; .#...#..
EQUB $7C ; .#####..
EQUB $82 ; #.....#.

; char_sprite_18 $11
EQUB $10 ; ...#....
EQUB $3C ; ..####..
EQUB $42 ; .#....#.
EQUB $43 ; .#....##
EQUB $C2 ; ##....#.
EQUB $42 ; .#....#.
EQUB $3C ; ..####..
EQUB $08 ; ....#...

; char_sprite_19 $12
EQUB $00 ; ........
EQUB $10 ; ...#....
EQUB $38 ; ..###...
EQUB $44 ; .#...#..
EQUB $C6 ; ##...##.
EQUB $44 ; .#...#..
EQUB $38 ; ..###...
EQUB $10 ; ...#....

; char_sprite_20 $13
EQUB $08 ; ....#...
EQUB $3C ; ..####..
EQUB $42 ; .#....#.
EQUB $C2 ; ##....#.
EQUB $43 ; .#....##
EQUB $42 ; .#....#.
EQUB $3C ; ..####..
EQUB $10 ; ...#....

; char_sprite_21 $14
EQUB $81 ; #......#
EQUB $42 ; .#....#.
EQUB $24 ; ..#..#..
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $24 ; ..#..#..
EQUB $42 ; .#....#.
EQUB $81 ; #......#

; char_sprite_22 $15
EQUB $81 ; #......#
EQUB $42 ; .#....#.
EQUB $3C ; ..####..
EQUB $3C ; ..####..
EQUB $3C ; ..####..
EQUB $3C ; ..####..
EQUB $42 ; .#....#.
EQUB $81 ; #......#

; char_sprite_23 $16
EQUB $81 ; #......#
EQUB $7E ; .######.
EQUB $7E ; .######.
EQUB $66 ; .##..##.
EQUB $66 ; .##..##.
EQUB $7E ; .######.
EQUB $7E ; .######.
EQUB $81 ; #......#

; char_sprite_24 $17
EQUB $18 ; ...##...
EQUB $24 ; ..#..#..
EQUB $24 ; ..#..#..
EQUB $42 ; .#....#.
EQUB $42 ; .#....#.
EQUB $24 ; ..#..#..
EQUB $24 ; ..#..#..
EQUB $18 ; ...##...

; char_sprite_25 $18
EQUB $00 ; ........
EQUB $18 ; ...##...
EQUB $24 ; ..#..#..
EQUB $42 ; .#....#.
EQUB $42 ; .#....#.
EQUB $24 ; ..#..#..
EQUB $18 ; ...##...
EQUB $00 ; ........

; char_sprite_26 ; $19
EQUB $00 ; ........
EQUB $18 ; ...##...
EQUB $66 ; .##..##.
EQUB $81 ; #......#
EQUB $81 ; #......#
EQUB $66 ; .##..##.
EQUB $18 ; ...##...
EQUB $00 ; ........

; char_sprite_27 ; $1A
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $10 ; ...#....
EQUB $38 ; ..###...
EQUB $54 ; .#.#.#..
EQUB $10 ; ...#....
EQUB $28 ; ..#.#...
EQUB $28 ; ..#.#...

; char_sprite_28 ; $1B
EQUB $00 ; ........
EQUB $7C ; .#####..
EQUB $92 ; #..#..#.
EQUB $92 ; #..#..#.
EQUB $EE ; ###.###.
EQUB $7C ; .#####..
EQUB $44 ; .#...#..
EQUB $38 ; ..###...

;----------------------------------------------------------------------------        
; UpdateHighscore
;----------------------------------------------------------------------------        
.UpdateHighscore                    ; L1CE0 Copy score to highscore   
        LDA SCREEN_ADDRESS-1,Y      ; score location
        STA HIGHSCORE_ADDRESS-1,Y   ; highscore position on screen
        STA L1039-1,Y               ; Updates stored hiscore
        DEY
        BNE UpdateHighscore         ; L1CE0
        RTS
;----------------------------------------------------------------------------        

;ORG $1CED        
; ???
; $1CED
EQUB $3C,$18,$18 

; $1CF0 Character Sprite set
.CharacterSet2
; char_s_sprite_1  ;$1C
EQUB $00 ; ........
EQUB $07 ; .....###
EQUB $1D ; ...###.#
EQUB $3F ; ..######
EQUB $6A ; .##.#.#.
EQUB $FF ; ########
EQUB $60 ; .##.....
EQUB $00 ; ........
    
; char_s_sprite_2 ; $20
EQUB $00 ; ........
EQUB $E0 ; ###.....
EQUB $B8 ; #.###...
EQUB $FC ; ######..
EQUB $56 ; .#.#.##.
EQUB $FF ; ########
EQUB $06 ; .....##.
EQUB $00 ; ........
    
; char_s_sprite_3 ; $21
EQUB $82 ; #.....#.
EQUB $42 ; .#....#.
EQUB $44 ; .#...#..
EQUB $09 ; ....#..#
EQUB $02 ; ......#.
EQUB $28 ; ..#.#...
EQUB $48 ; .#..#...
EQUB $84 ; #....#..
    
; char_s_sprite_4 ; $22
EQUB $02 ; ......#.
EQUB $C4 ; ##...#..
EQUB $24 ; ..#..#..
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $26 ; ..#..##.
EQUB $41 ; .#.....#
    
; char_s_sprite_5 ; $23
EQUB $00 ; ........
EQUB $40 ; .#......
EQUB $01 ; .......#
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $80 ; #.......
EQUB $02 ; ......#.
EQUB $00 ; ........
    
; char_s_sprite_6 ; $24 Ship 1 full $26 $24
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $5A ; .#.##.#.
EQUB $5A ; .#.##.#.
EQUB $7E ; .######.
EQUB $FF ; ########
EQUB $FF ; ########
    
; char_s_sprite_7 ; $22 ship 2 left $27 $25
EQUB $40 ; .#......
EQUB $41 ; .#.....#
EQUB $61 ; .##....#
EQUB $73 ; .###..##
EQUB $7F ; .#######
EQUB $7F ; .#######
EQUB $7F ; .#######
EQUB $61 ; .##....#
    
; char_s_sprite_8 ; $23 ship 2 middle $28 $26
EQUB $FF ; ########
EQUB $FF ; ########
EQUB $E7 ; ###..###
EQUB $DB ; ##.##.##
EQUB $DB ; ##.##.##
EQUB $E7 ; ###..###
EQUB $DB ; ##.##.##
EQUB $C3 ; ##....##
    
; char_s_sprite_9 ; $24 ship 2 right $29 $27
EQUB $02 ; ......#.
EQUB $82 ; #.....#.
EQUB $86 ; #....##.
EQUB $CE ; ##..###.
EQUB $FE ; #######.
EQUB $FE ; #######.
EQUB $FE ; #######.
EQUB $86 ; #....##.
    
; char_s_sprite_10 ; $25 Ship 1 left $2A $28
EQUB $03 ; ......##
EQUB $03 ; ......##
EQUB $03 ; ......##
EQUB $0B ; ....#.##
EQUB $0B ; ....#.##
EQUB $0F ; ....####
EQUB $1F ; ...#####
EQUB $1F ; ...#####
    
; char_s_sprite_11 ; $26 Ship 1 right $2B $29
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $40 ; .#......
EQUB $40 ; .#......
EQUB $C0 ; ##......
EQUB $E0 ; ###.....
EQUB $E0 ; ###.....
    
; char_s_sprite_12 ; $27 ship 2 left $2C $2A
EQUB $08 ; ....#...
EQUB $08 ; ....#...
EQUB $0C ; ....##..
EQUB $0E ; ....###.
EQUB $0F ; ....####
EQUB $0F ; ....####
EQUB $0F ; ....####
EQUB $0C ; ....##..
    
; char_s_sprite_13 ; $28 ship 2 middle left $2D $2B
EQUB $1F ; ...#####
EQUB $3F ; ..######
EQUB $3C ; ..####..
EQUB $7B ; .####.##
EQUB $FB ; #####.##
EQUB $FC ; ######..
EQUB $FB ; #####.##
EQUB $78 ; .####...
    
; char_s_sprite_14 ; $29 ship 2 middle right $2E $2C
EQUB $E0 ; ###.....
EQUB $F0 ; ####....
EQUB $70 ; .###....
EQUB $B9 ; #.###..#
EQUB $BF ; #.######
EQUB $7F ; .#######
EQUB $FF ; ########
EQUB $30 ; ..##....
    
; char_s_sprite_15 ; $2A ship 2 right $2F $2D
EQUB $40 ; .#......
EQUB $40 ; .#......
EQUB $C0 ; ##......
EQUB $C0 ; ##......
EQUB $C0 ; ##......
EQUB $C0 ; ##......
EQUB $C0 ; ##......
EQUB $C0 ; ##......
    
; char_s_sprite_16 bullet below $30 $2E
EQUB $00 ; ........
EQUB $CC ; ##..##..
EQUB $CC ; ##..##..
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_17 $31 $2F
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $40 ; .#......
EQUB $40 ; .#......
EQUB $40 ; .#......
EQUB $40 ; .#......
    
; char_s_sprite_18 $30
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $18 ; ...##...
    
; char_s_sprite_19 $31
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $02 ; ......#.
EQUB $02 ; ......#.
EQUB $02 ; ......#.
EQUB $02 ; ......#.
    
; char_s_sprite_20 $32
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $08 ; ....#...
EQUB $08 ; ....#...
EQUB $08 ; ....#...
EQUB $08 ; ....#...
    
; char_s_sprite_21 $33
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $03 ; ......##
EQUB $03 ; ......##
EQUB $03 ; ......##
EQUB $03 ; ......##
    
; char_s_sprite_22 $34
EQUB $40 ; .#......
EQUB $40 ; .#......
EQUB $40 ; .#......
EQUB $40 ; .#......
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_23 $35
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $18 ; ...##...
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_24 $36
EQUB $02 ; ......#.
EQUB $02 ; ......#.
EQUB $02 ; ......#.
EQUB $02 ; ......#.
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_25 $37
EQUB $08 ; ....#...
EQUB $08 ; ....#...
EQUB $08 ; ....#...
EQUB $08 ; ....#...
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_26 $38
EQUB $03 ; ......##
EQUB $03 ; ......##
EQUB $03 ; ......##
EQUB $03 ; ......##
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_27 score $3B
EQUB $00 ; ........
EQUB $DB ; ##.##.##
EQUB $92 ; #..#..#.
EQUB $D2 ; ##.#..#.
EQUB $52 ; .#.#..#.
EQUB $DB ; ##.##.##
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_28 $3C
EQUB $00 ; ........
EQUB $B3 ; #.##..##
EQUB $AA ; #.#.#.#.
EQUB $B3 ; #.##..##
EQUB $B2 ; #.##..#.
EQUB $AB ; #.#.#.##
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_29 high $3D
EQUB $00 ; ........
EQUB $AB ; #.#.#.##
EQUB $AA ; #.#.#.#.
EQUB $EA ; ###.#.#.
EQUB $AA ; #.#.#.#.
EQUB $AB ; #.#.#.##
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_30 $3E
EQUB $00 ; ........
EQUB $A8 ; #.#.#...
EQUB $2A ; ..#.#.#.
EQUB $B8 ; #.###...
EQUB $AA ; #.#.#.#.
EQUB $A8 ; #.#.#...
EQUB $00 ; ........
EQUB $00 ; ........
    
; char_s_sprite_31 (c) not used?
EQUB $3C ; ..####..
EQUB $42 ; .#....#.
EQUB $99 ; #..##..#
EQUB $A1 ; #.#....#
EQUB $A1 ; #.#....#
EQUB $99 ; #..##..#
EQUB $42 ; .#....#.
EQUB $3C ; ..####..